appName: financialAnalysis
logLevel: WARN

system:
  poolSize: 5

file:
  tickerSymbols: resources/tickerSymbols/tickerSymbols.txt

# tickers
  fetchedTicker: resources\\fetched\\ticker
  crawledFinancials: resources\\crawled\\financials

  processedTicker: resources\\processed\\ticker
  processedFinancials: resources\\processed\\financials

url:
  financials: https://finance.yahoo.com/quote/{0}/financials?p={0}

stock:
  period:
    start: "2010-01-01"
    end: "2019-12-30"
  header: "open, close, high, low, volumn, amount"
  features:
    Volumn_Delta: "volume_delta"
    Open_+2days: "open_2_d"
    Open_-2days: "open_2_d"
    CR_5days: "cr-ma1"
    CR_10days: "cr-ma2"
    CR_20days: "cr-ma3"

    # Stochastic oscillator
    KDJK: "kdjk"
    KDJD: "kdjd"
    KDJJ: "kdjj"

    # 2 days simple moving average on open price
    Open_+2sma: "open_2_sma"

    # MACD MACD signal line MACD histogram
    MACD: "macd"
    MACDS: "macds"
    MACDH: "macdh"

    # Bolliger uppser & lower band
    Bolliger: "boll"
    BolligerUpper: "boll_ub"
    BolligerLower: "boll_lb"

    # relative strength index
    RSI_6days: "rsi_6"
    RSI_12days: "rsi_12"

    # Williams Overbought/Oversold index
    WR_10days: "wr_10"
    WR_6days: "wr_6"

    # DMA difference of 10 and 50 moving average
    DMA: "dma"


